
services:

  spotik-app:
    container_name: spotik-app
    build:
        context: .
        dockerfile: Dockerfile
    restart: unless-stopped
    ports:
        - 8000:80
    environment:
        # Настройка подключения к БД (используем имя сервиса spotik-pgdb вместо localhost)
        DATABASE_URL: "postgresql://app:!ChangeMe!@spotik-pgdb:5432/app?serverVersion=16&charset=utf8"
        APP_ENV: dev
        APP_SECRET: ChangeMe
        MERCURE_URL: http://spotik-mercure/.well-known/mercure
        MERCURE_PUBLIC_URL: http://localhost:3001/.well-known/mercure
        MERCURE_JWT_TOKEN: "!ChangeThisMercureHubJWTSecretKey!"
    depends_on:
        spotik-pgdb:
            condition: service_healthy

    volumes:
        - .:/app
        - ./var:/app/var
###> doctrine/doctrine-bundle ###
  spotik-pgdb:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

###> symfony/mercure-bundle ###
  spotik-mercure:
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      # Uncomment the following line to disable HTTPS,
      #SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      # Set the URL of your Symfony project (without trailing slash!) as value of the cors_origins directive
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins http://127.0.0.1:8000
    # Comment the following line to disable the development mode
    command: /usr/bin/caddy run --config /etc/caddy/dev.Caddyfile
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost/healthz"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - mercure_data:/data
      - mercure_config:/config
    ports:
      - "3001:80"
###< symfony/mercure-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###

###> symfony/mercure-bundle ###
  mercure_data:
  mercure_config:
###< symfony/mercure-bundle ###
